
--[[
Each new term in the Fibonacci sequence
is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
--]]

-- the proper way is to create a generator or constructor and use a for loop

function solution(n)
end

c,i1,i2 = 2,1,2

function nextfibonacci()
 c,i1,i2 = c+1, i2, i1 + i2
end

function sequence(n)
 local i1,i2 = 1,2
 for i=1,10 do
  print(i1)
  i1,i2 = i2, i1 + i2
 end
end

function solution(n)
 local i1,i2 = 1,2
 local sum = 0
 while i1 < 4000000 do
  if i1 % 2 == 0 then sum = sum + i1 end
  i1,i2 = i2, i1 + i2
 end
 print(sum)
end

solution()